package com.it.elec.model;


import java.util.Date;

/**
 * ElecosSystemddl generated by hbm2java
 */
public class ElecosSystemDDL implements java.io.Serializable {

	private static final long serialVersionUID = 5267277299579094533L;
	private Integer seqId;
	private String keyword;
	private int ddlcode;
	private String ddlname;
	private Date createTime;
	private Date updateTime;

	public ElecosSystemDDL() {
	}

	public ElecosSystemDDL(String keyword, int ddlcode, String ddlname, Date createTime) {
		this.keyword = keyword;
		this.ddlcode = ddlcode;
		this.ddlname = ddlname;
		this.createTime = createTime;
	}

	public ElecosSystemDDL(String keyword, int ddlcode, String ddlname, Date createTime, Date updateTime) {
		this.keyword = keyword;
		this.ddlcode = ddlcode;
		this.ddlname = ddlname;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Integer getSeqId() {
		return this.seqId;
	}

	public void setSeqId(Integer seqId) {
		this.seqId = seqId;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public int getDdlcode() {
		return this.ddlcode;
	}

	public void setDdlcode(int ddlcode) {
		this.ddlcode = ddlcode;
	}

	public String getDdlname() {
		return this.ddlname;
	}

	public void setDdlname(String ddlname) {
		this.ddlname = ddlname;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	
	/**
	 * *******************非持久化javabean属性**************************
	 * */
	
	/**
	 * 数据类型
	 */
	private String keywordname;
	/**
	 * 用来判断是新增数据类型，还是对已有数据类型进行编辑修改
	 * 判断标志：typeflag="new",是新增
	 * 			typeflag="add",是更新
	 */
	private String typeflag;
	/**
	 * 数据项的值，string类型的数组存放
	 */
	private String[] itemname;

	public String getKeywordname() {
		return keywordname;
	}

	public void setKeywordname(String keywordname) {
		this.keywordname = keywordname;
	}

	public String getTypeflag() {
		return typeflag;
	}

	public void setTypeflag(String typeflag) {
		this.typeflag = typeflag;
	}

	public String[] getItemname() {
		return itemname;
	}

	public void setItemname(String[] itemname) {
		this.itemname = itemname;
	}
	

}
