package com.it.elec.model;
// Generated 2017-7-6 14:59:26 by Hibernate Tools 3.6.0

/**
 * ElecosRolePopedom generated by hbm2java
 */
public class ElecosRolePopedom implements java.io.Serializable {

	private static final long serialVersionUID = -6408451304072743731L;

	public ElecosRolePopedom(Integer roleId, String mid, String pid) {
		
		this.roleId = roleId;
		this.mid = mid;
		this.pid = pid;
	}

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getMid() {
		return mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	public String getPid() {
		return pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	private Integer roleId;
	private String mid;
	private String pid;
	
	public ElecosRolePopedom() {
	}

	
}
