package com.it.elec.model;
import java.util.Date;

/**
 * ElecosRole generated by hbm2java
 */
public class ElecosRole implements java.io.Serializable {

	private static final long serialVersionUID = -7135437276436233501L;
	private Integer roleId;
	private String roleName;
	private Date createTime;
	private Date updateTime;

	public ElecosRole() {
	}

	public ElecosRole(String roleName, Date createTime) {
		this.roleName = roleName;
		this.createTime = createTime;
	}

	public ElecosRole(String roleName, Date createTime, Date updateTime) {
		this.roleName = roleName;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
